# Generated by Django 4.1.2 on 2022-10-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastStatDatabase',
            fields=[
                ('datid', models.IntegerField(primary_key=True, serialize=False)),
                ('datname', models.CharField(max_length=16)),
                ('xact_commit', models.BigIntegerField(null=True)),
                ('xact_rollback', models.BigIntegerField(null=True)),
                ('blks_read', models.BigIntegerField(null=True)),
                ('blks_hit', models.BigIntegerField(null=True)),
                ('tup_returned', models.BigIntegerField(null=True)),
                ('tup_fetched', models.BigIntegerField(null=True)),
                ('tup_inserted', models.BigIntegerField(null=True)),
                ('tup_updated', models.BigIntegerField(null=True)),
                ('tup_deleted', models.BigIntegerField(null=True)),
                ('conflicts', models.BigIntegerField(null=True)),
                ('temp_files', models.BigIntegerField(null=True)),
                ('temp_bytes', models.BigIntegerField(null=True)),
                ('deadlocks', models.BigIntegerField(null=True)),
                ('blk_read_time', models.FloatField(null=True)),
                ('blk_write_time', models.FloatField(null=True)),
                ('stats_reset', models.DateTimeField(null=True)),
                ('datsize', models.BigIntegerField(null=True)),
                ('datsize_delta', models.BigIntegerField(null=True)),
                ('datistemplate', models.BigIntegerField(null=True)),
                ('session_time', models.FloatField(null=True)),
                ('active_time', models.FloatField(null=True)),
                ('idle_in_transaction_time', models.FloatField(null=True)),
                ('sessions', models.BigIntegerField(null=True)),
                ('sessions_abandoned', models.BigIntegerField(null=True)),
                ('sessions_fatal', models.BigIntegerField(null=True)),
                ('sessions_killed', models.BigIntegerField(null=True)),
                ('checksum_failures', models.BigIntegerField(null=True)),
                ('checksum_last_failure', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'last_stat_database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastStatTablespace',
            fields=[
                ('tablespace_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tablespace_name', models.CharField(max_length=16)),
                ('tablespace_path', models.TextField()),
                ('size', models.IntegerField()),
                ('size_delta', models.IntegerField()),
            ],
            options={
                'db_table': 'last_stat_tablespaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('topn', models.PositiveSmallIntegerField(default=20)),
                ('max_sample_age', models.PositiveIntegerField(default=7, verbose_name='')),
                ('track_sample_timings', models.BooleanField(default=False)),
                ('max_query_length', models.PositiveIntegerField(default=20000)),
                ('frequency', models.PositiveIntegerField(default=1800)),
                ('last_sample_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='Tablespaces',
            fields=[
                ('tablespace_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tablespace_name', models.CharField(max_length=16)),
                ('tablespace_path', models.TextField()),
                ('last_sample_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tablespaces_list',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.server')),
            ],
            options={
                'db_table': 'samples',
                'unique_together': {('sample_id', 'server')},
            },
        ),
        migrations.CreateModel(
            name='SampleStatTablespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('size_delta', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.sample')),
                ('tablespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.tablespaces')),
            ],
            options={
                'db_table': 'sample_stat_tablespaces',
                'unique_together': {('sample_id', 'tablespace')},
            },
        ),
        migrations.CreateModel(
            name='SampleStatDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datid', models.IntegerField()),
                ('datname', models.CharField(max_length=16)),
                ('xact_commit', models.BigIntegerField(null=True)),
                ('xact_rollback', models.BigIntegerField(null=True)),
                ('blks_read', models.BigIntegerField(null=True)),
                ('blks_hit', models.BigIntegerField(null=True)),
                ('tup_returned', models.BigIntegerField(null=True)),
                ('tup_fetched', models.BigIntegerField(null=True)),
                ('tup_inserted', models.BigIntegerField(null=True)),
                ('tup_updated', models.BigIntegerField(null=True)),
                ('tup_deleted', models.BigIntegerField(null=True)),
                ('conflicts', models.BigIntegerField(null=True)),
                ('temp_files', models.BigIntegerField(null=True)),
                ('temp_bytes', models.BigIntegerField(null=True)),
                ('deadlocks', models.BigIntegerField(null=True)),
                ('blk_read_time', models.FloatField(null=True)),
                ('blk_write_time', models.FloatField(null=True)),
                ('stats_reset', models.DateTimeField(null=True)),
                ('datsize', models.BigIntegerField(null=True)),
                ('datsize_delta', models.BigIntegerField(null=True)),
                ('datistemplate', models.BigIntegerField(null=True)),
                ('session_time', models.FloatField(null=True)),
                ('active_time', models.FloatField(null=True)),
                ('idle_in_transaction_time', models.FloatField(null=True)),
                ('sessions', models.BigIntegerField(null=True)),
                ('sessions_abandoned', models.BigIntegerField(null=True)),
                ('sessions_fatal', models.BigIntegerField(null=True)),
                ('sessions_killed', models.BigIntegerField(null=True)),
                ('checksum_failures', models.BigIntegerField(null=True)),
                ('checksum_last_failure', models.DateTimeField(null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.sample')),
            ],
            options={
                'db_table': 'sample_stat_database',
                'unique_together': {('sample', 'datid')},
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW last_stat_database AS (
                SELECT
                    dbs.datid,
                    dbs.datname,
                    dbs.xact_commit,
                    dbs.xact_rollback,
                    dbs.blks_read,
                    dbs.blks_hit,
                    dbs.tup_returned,
                    dbs.tup_fetched,
                    dbs.tup_inserted,
                    dbs.tup_updated,
                    dbs.tup_deleted,
                    dbs.conflicts,
                    dbs.temp_files,
                    dbs.temp_bytes,
                    dbs.deadlocks,
                    CASE WHEN (SELECT setting::bigint < 12000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL
                        ELSE dbs.checksum_failures
                    END AS checksum_failures,
                    CASE WHEN (SELECT setting::bigint < 12000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL
                        ELSE dbs.checksum_last_failure
                    END AS checksum_last_failure,
                    dbs.blk_read_time,
                    dbs.blk_write_time,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL 
                        ELSE dbs.session_time
                    END AS session_time,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL 
                        ELSE dbs.active_time
                    END AS active_time,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL
                        ELSE dbs.idle_in_transaction_time
                    END AS idle_in_transaction_time,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL 
                        ELSE dbs.sessions 
                    END AS sessions,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL
                        ELSE dbs.sessions_abandoned
                    END AS sessions_abandoned,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL 
                        ELSE dbs.sessions_fatal
                    END AS sessions_fatal,
                    CASE WHEN (SELECT setting::bigint < 14000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                        THEN NULL 
                        ELSE dbs.sessions_killed
                    END AS sessions_killed,
                    dbs.stats_reset,
                    pg_database_size(dbs.datid) AS datsize,
                    0 AS datsize_delta,
                    db.datistemplate 
                FROM pg_catalog.pg_stat_database dbs
                JOIN pg_catalog.pg_database db ON (dbs.datid = db.oid)
                WHERE dbs.datname IS NOT NULL
            )
            """,
            "DROP MATERIALIZED VIEW last_stat_database;"
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW last_stat_tablespaces AS (
                SELECT 
                    oid as tablespace_id,
                    spcname as tablespace_name,
                    pg_catalog.pg_tablespace_location(oid) as tablespace_path,
                    pg_catalog.pg_tablespace_size(oid) as size,
                    0 as size_delta
                FROM pg_catalog.pg_tablespace
            )
            """,
            "DROP MATERIALIZED VIEW last_stat_tablespaces;"
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW last_stat_cluster AS (
                SELECT
                    checkpoints_timed,
                    checkpoints_req,
                    checkpoint_write_time,
                    checkpoint_sync_time,
                    buffers_checkpoint,
                    buffers_clean,
                    maxwritten_clean,
                    buffers_backend,
                    buffers_backend_fsync,
                    buffers_alloc,
                    stats_reset,
                        CASE WHEN (SELECT setting::bigint >= 10000 FROM pg_catalog.pg_settings WHERE name = 'server_version_num')
                            THEN
                                CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 
                                    ELSE pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(),'0/00000000') 
                                END
                            ELSE 0
                        END as wal_size
                FROM pg_catalog.pg_stat_bgwriter
            )
            """,
            "DROP MATERIALIZED VIEW last_stat_cluster;"
        )
    ]
