# Generated by Django 4.1.2 on 2022-10-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'samples',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('max_sample_age', models.PositiveIntegerField(null=True, verbose_name='')),
                ('last_sample_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='StatDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xact_commit', models.BigIntegerField(null=True)),
                ('xact_rollback', models.BigIntegerField(null=True)),
                ('blks_read', models.BigIntegerField(null=True)),
                ('blks_hit', models.BigIntegerField(null=True)),
                ('tup_returned', models.BigIntegerField(null=True)),
                ('tup_fetched', models.BigIntegerField(null=True)),
                ('tup_inserted', models.BigIntegerField(null=True)),
                ('tup_updated', models.BigIntegerField(null=True)),
                ('tup_deleted', models.BigIntegerField(null=True)),
                ('conflicts', models.BigIntegerField(null=True)),
                ('temp_files', models.BigIntegerField(null=True)),
                ('temp_bytes', models.BigIntegerField(null=True)),
                ('deadlocks', models.BigIntegerField(null=True)),
                ('blk_read_time', models.FloatField(null=True)),
                ('blk_write_time', models.FloatField(null=True)),
                ('stats_reset', models.DateTimeField(null=True)),
                ('datsize', models.BigIntegerField(null=True)),
                ('datsize_delta', models.BigIntegerField(null=True)),
                ('datistemplate', models.BigIntegerField(null=True)),
                ('session_time', models.FloatField(null=True)),
                ('active_time', models.FloatField(null=True)),
                ('idle_in_transaction_time', models.FloatField(null=True)),
                ('sessions', models.BigIntegerField(null=True)),
                ('sessions_abandoned', models.BigIntegerField(null=True)),
                ('sessions_fatal', models.BigIntegerField(null=True)),
                ('sessions_killed', models.BigIntegerField(null=True)),
                ('checksum_failures', models.BigIntegerField(null=True)),
                ('checksum_last_failure', models.DateTimeField(null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.sample')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.server')),
            ],
            options={
                'db_table': 'sample_stat_database',
                'unique_together': {('server', 'sample')},
            },
        ),
        migrations.CreateModel(
            name='LastStatDatabase',
            fields=[
                ('statdatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbadmin.statdatabase')),
            ],
            options={
                'db_table': 'last_stat_database',
            },
            bases=('dbadmin.statdatabase',),
        ),
        migrations.AddField(
            model_name='sample',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.server'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('sample_id', 'server')},
        ),
    ]
