# Generated by Django 4.1.2 on 2022-10-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastStatTablespace',
            fields=[
                ('tablespace_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tablespace_name', models.CharField(max_length=16)),
                ('tablespace_path', models.TextField()),
                ('size', models.IntegerField()),
                ('size_delta', models.IntegerField()),
            ],
            options={
                'db_table': 'last_stat_tablespaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tablespaces',
            fields=[
                ('tablespace_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tablespace_name', models.CharField(max_length=16)),
                ('tablespace_path', models.TextField()),
                ('last_sample_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tablespaces_list',
            },
        ),
        migrations.CreateModel(
            name='SampleStatTablespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('size_delta', models.IntegerField()),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.sample')),
                ('tablespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbadmin.tablespaces')),
            ],
            options={
                'db_table': 'sample_stat_tablespaces',
                'unique_together': {('sample_id', 'tablespace')},
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW last_stat_tablespaces AS (
                SELECT 
                    oid as tablespace_id,
                    spcname as tablespace_name,
                    pg_catalog.pg_tablespace_location(oid) as tablespace_path,
                    pg_catalog.pg_tablespace_size(oid) as size,
                    0 as size_delta
                FROM pg_catalog.pg_tablespace
            )
            """,
            "DROP MATERIALIZED VIEW last_stat_tablespaces;"
        ),
    ]
